export const subjectLines = [
  "Quick question about {company}'s backend",
  "Is {company} scaling operations this quarter?",
  "A completely biased suggestion for {company}",
  "How {company} can save 10 hours a week",
  "Your tech stack vs our automation",
  "Thought you might like this resource on scaling",
  "Quick idea for {first_name}",
  "Is this a crazy idea for {company}?",
  "Backend automation (not another sales pitch... mostly)",
  "Don't open this if you hate saving time",
  "Are you the right person to talk about automation?",
  "Just a quick heads up for {first_name}",
  "Can I borrow 2 minutes of your time?",
  "Idea for {company}'s growth",
  "Scaling {company} without adding headcount",
  "Question about your current workflow",
  "A better way to handle {company}'s operations",
  "Are you dealing with this issue too?",
  "An easier way to manage growth at {company}",
  "Quick question for {first_name}",
  "Hoping to connect regarding {company}",
  "Resource: Streamlining ops for fast-growing startups",
  "A quick win for your team",
  "Is {company} ready for next quarter?",
  "One quick thing about your automation",
  "A slightly better way to do things at {company}",
  "Thoughts on your current stack?",
  "How to stop doing manual tasks",
  "Are you still doing this manually?",
  "Quick intro + a question",
  "Could this work for {company}?",
  "A resource for your team",
  "Is this on your radar?",
  "Quick check-in regarding automation",
  "A crazy thought for {company}",
  "Your time is valuable, so I'll be quick",
  "A different approach for {company}",
  "Quick question about your scaling strategy",
  "Are you open to a new idea?",
  "A resource that might actually be useful",
  "How are you handling this at {company}?",
  "A quick idea to bounce off you",
  "Is {company} facing this bottleneck?",
  "A small tweak for a big win",
  "Quick thought on your operations",
  "A different perspective for {company}",
  "Are you the best person to ask?",
  "A resource for {company}'s next phase",
  "Quick question about your current setup",
  "A less painful way to scale",
  "Is {company} struggling with manual work?",
  "A quick idea for your backend",
  "Thoughts on this approach?",
  "A resource that could save {company} time",
  "Quick check-in on your automation",
  "A different way to handle this",
  "Is this a priority for {company} right now?",
  "A small suggestion for {first_name}",
  "Quick question on your growth plans",
  "A resource for your operations team",
  "Are you looking to streamline things?",
  "A quick thought for {company}",
  "Thoughts on your current process?",
  "A better way to manage this",
  "Is {company} looking for a change?",
  "A quick intro + an idea",
  "Question about your tech stack",
  "A resource for your current phase",
  "Are you dealing with these challenges?",
  "A quick suggestion for your team",
  "Thoughts on your automation strategy?",
  "A different approach to scaling",
  "Is {company} ready for this?",
  "A quick check-in for {first_name}",
  "Question about your operations",
  "A resource that could help {company}",
  "Are you open to streamlining?",
  "A quick idea to run by you",
  "Thoughts on your current workflow?",
  "A better approach for {company}",
  "Is this an issue for your team?",
  "A quick suggestion for {company}",
  "Question about your scaling plans",
  "A resource for your next quarter",
  "Are you looking for a better way?",
  "A quick thought on your setup",
  "Thoughts on this idea?",
  "A different way to manage growth",
  "Is {company} facing these issues?",
  "A quick check-in regarding your stack",
  "Question about your current approach",
  "A resource that might help your team",
  "Are you open to a different perspective?",
  "A quick idea for {company}'s growth",
  "Thoughts on your automation plans?",
  "A better way to handle growth",
  "Is this a focus for {company}?",
  "A quick suggestion for your operations",
  "Question about your tech strategy",
  "A resource for your current challenges",
];

export const emailBodies = [
  "Hi {first_name},\n\nJust came across {company} and was wondering how you currently handle your backend automation?\n\nI built a tool that saves teams around 10 hours a week on this. Would you be open to a quick chat to see if it makes sense for you?",
  "Hi {first_name},\n\nNoticed {company} is growing fast. I put together a quick 1-pager on how similar companies are streamlining their operations to handle scale without adding headcount.\n\nHappy to send it over if you think it would be useful?",
  "Hi {first_name},\n\nJust bumping this to the top of your inbox. Let me know if you have any questions!",
  "Hi {first_name},\n\nI'll keep this short. We help companies like yours automate the boring stuff. Is this something you're looking into for {company}?",
  "Hi {first_name},\n\nAre you the right person at {company} to speak with regarding operations and automation? If not, could you point me in the right direction?",
  "Hi {first_name},\n\nI was doing some research on {company} and noticed a few areas where our tool could probably save your team a lot of manual work. Open to a 5-minute chat next week?",
  "Hi {first_name},\n\nQuick question: how are you currently managing your backend operations? We've found a way to cut that time in half for most teams. Worth a quick look?",
  "Hi {first_name},\n\nI know you're busy, so I'll get straight to the point. We can help {company} scale without the growing pains of manual processes. Are you open to seeing how?",
  "Hi {first_name},\n\nJust following up on my previous note. Let me know if this is a bad time or if I should reach out to someone else at {company}.",
  "Hi {first_name},\n\nThought I'd share a quick case study on how we helped a company similar to {company} save 20 hours a week. Let me know if you want to see the details.",
  "Hi {first_name},\n\nIs streamlining operations a priority for {company} this quarter? If so, we should probably talk.",
  "Hi {first_name},\n\nI've been following {company}'s growth and wanted to reach out. We specialize in helping companies scale their operations smoothly. Any interest in a brief intro call?",
  "Hi {first_name},\n\nI'm reaching out because we've developed a new approach to backend automation that I think {company} could really benefit from. Can I send you a short video explaining how?",
  "Hi {first_name},\n\nJust checking in to see if you had a chance to review my last email. No worries if you're swamped, just let me know!",
  "Hi {first_name},\n\nI wanted to share a quick resource that might be helpful for your team at {company} as you continue to grow. Want me to send the link?",
  "Hi {first_name},\n\nAre you currently looking for ways to improve efficiency at {company}? We have a solution that might be exactly what you need.",
  "Hi {first_name},\n\nI'll be brief. We help teams automate manual tasks. Is this something {company} is struggling with right now?",
  "Hi {first_name},\n\nJust wanted to see if you're the best contact at {company} for discussions around automation and operations?",
  "Hi {first_name},\n\nI was impressed by what {company} is doing and wanted to connect. We help similar companies optimize their workflows. Open to a quick chat?",
  "Hi {first_name},\n\nQuick question: is {company} currently evaluating new tools for automation? If so, I'd love to show you what we're working on.",
  "Hi {first_name},\n\nI know you get a lot of emails, so I'll make this quick. We can save {company} time and money by automating your backend. Want to learn more?",
  "Hi {first_name},\n\nJust following up again. If this isn't relevant to you, I'll stop bugging you. Just let me know either way!",
  "Hi {first_name},\n\nThought this article on scaling operations might be relevant to {company}. Let me know if you find it useful.",
  "Hi {first_name},\n\nIs {company} planning any major operational changes this year? If so, we might be able to help.",
  "Hi {first_name},\n\nI'm reaching out because I believe our tool could significantly improve your team's workflow at {company}. Can we schedule a brief call?",
  "Hi {first_name},\n\nI wanted to share a quick idea on how {company} could streamline its processes. Can I send over a brief summary?",
  "Hi {first_name},\n\nAre you currently satisfied with your backend operations at {company}? If there's room for improvement, we should talk.",
  "Hi {first_name},\n\nI'll keep this short and sweet. We do automation. It saves time. Is {company} interested?",
  "Hi {first_name},\n\nJust wanted to check if you're the right person to handle this, or if there's someone else at {company} I should contact.",
  "Hi {first_name},\n\nI've been keeping an eye on {company} and think our solution could be a great fit for your current needs. Open to exploring this?",
  "Hi {first_name},\n\nQuick question: what's the biggest operational bottleneck at {company} right now? We might be able to help solve it.",
  "Hi {first_name},\n\nI know your time is valuable. We help companies like {company} reduce manual work by 50%. Want to see how?",
  "Hi {first_name},\n\nJust touching base on my previous email. Let me know if you're interested or if I should follow up later.",
  "Hi {first_name},\n\nThought you might be interested in a recent webinar we hosted on operations scaling. Let me know if you want the recording.",
  "Hi {first_name},\n\nIs {company} currently looking for ways to cut costs and improve efficiency? If so, we should connect.",
  "Hi {first_name},\n\nI'm reaching out because I have a few ideas on how {company} could optimize its backend. Can we chat for 10 minutes next week?",
  "Hi {first_name},\n\nI wanted to share a quick tool that could help {company} automate its workflows. Want me to send the details?",
  "Hi {first_name},\n\nAre you the decision-maker for operational tools at {company}? If not, could you point me to them?",
  "Hi {first_name},\n\nI'll be quick. We help teams streamline their operations. Is this something {company} needs right now?",
  "Hi {first_name},\n\nJust wanted to see if you received my previous message. No pressure, just following up.",
  "Hi {first_name},\n\nI was impressed by {company}'s recent news and wanted to connect. We help companies handle growth smoothly. Open to a chat?",
  "Hi {first_name},\n\nQuick question: how much time does your team spend on manual tasks each week? We might be able to significantly reduce that.",
  "Hi {first_name},\n\nI know you're busy. We offer a solution that can automate {company}'s backend. Interested in learning more?",
  "Hi {first_name},\n\nJust following up one last time. If I don't hear back, I'll assume it's not a priority right now.",
  "Hi {first_name},\n\nThought this guide on automation might be useful for your team at {company}. Let me know if you want a copy.",
  "Hi {first_name},\n\nIs {company} currently dealing with any operational challenges? We specialize in solving those.",
  "Hi {first_name},\n\nI'm reaching out because I think our tool could be a game-changer for {company}. Can we schedule a brief demo?",
  "Hi {first_name},\n\nI wanted to share a quick case study that highlights how we helped a similar company scale. Want to take a look?",
  "Hi {first_name},\n\nAre you currently exploring new ways to improve {company}'s operations? We should definitely talk.",
  "Hi {first_name},\n\nI'll keep this brief. We automate backend processes. Is {company} looking for this kind of solution?",
  "Hi {first_name},\n\nJust checking in to see if you're the right person to speak with regarding this?",
  "Hi {first_name},\n\nI've been following {company} and think our solution could help you scale more efficiently. Open to a quick call?",
  "Hi {first_name},\n\nQuick question: is {company} currently using any automation tools? We might be able to offer a better alternative.",
  "Hi {first_name},\n\nI know you get a ton of emails. We help teams like {company} save time. Want to see how?",
  "Hi {first_name},\n\nJust following up on my previous note. Let me know if this is relevant to you.",
  "Hi {first_name},\n\nThought you might find this whitepaper on operations scaling interesting. Let me know if you want the link.",
  "Hi {first_name},\n\nIs improving operational efficiency on {company}'s roadmap this year? If so, we should connect.",
  "Hi {first_name},\n\nI'm reaching out because I have some ideas on how {company} could streamline its workflows. Can we chat next week?",
  "Hi {first_name},\n\nI wanted to share a quick resource that could help your team at {company}. Want me to send it over?",
  "Hi {first_name},\n\nAre you the person responsible for operations at {company}? If not, who should I contact?",
  "Hi {first_name},\n\nI'll be short. We help companies automate their backend. Is {company} interested in this?",
  "Hi {first_name},\n\nJust wanted to see if you had a chance to read my last email. No worries if you've been busy.",
  "Hi {first_name},\n\nI was impressed by {company}'s recent growth and wanted to connect. We help companies manage scale. Open to a chat?",
  "Hi {first_name},\n\nQuick question: what's the most time-consuming part of your operations at {company}? We might be able to automate it.",
  "Hi {first_name},\n\nI know your time is precious. We can help {company} automate its backend and save hours each week. Want to learn more?",
  "Hi {first_name},\n\nJust following up again. If this isn't a good time, let me know when I should reach back out.",
  "Hi {first_name},\n\nThought this article on automation trends might be relevant to {company}. Let me know if you want to read it.",
  "Hi {first_name},\n\nIs {company} currently facing any scaling challenges? We might be able to help.",
  "Hi {first_name},\n\nI'm reaching out because I believe our solution could greatly benefit {company}. Can we schedule a brief call?",
  "Hi {first_name},\n\nI wanted to share a quick idea on how to improve {company}'s operations. Can I send you a short summary?",
  "Hi {first_name},\n\nAre you currently looking for ways to streamline {company}'s workflows? We should talk.",
  "Hi {first_name},\n\nI'll keep this simple. We automate things. It saves time. Is {company} interested?",
  "Hi {first_name},\n\nJust checking if you're the right contact for this, or if there's someone else I should reach out to.",
  "Hi {first_name},\n\nI've been keeping an eye on {company} and think our tool could be a great fit. Open to exploring this?",
  "Hi {first_name},\n\nQuick question: is {company} currently satisfied with its automation setup? If there's room for improvement, we should connect.",
  "Hi {first_name},\n\nI know you're busy. We help companies like {company} reduce manual work. Want to see a quick demo?",
  "Hi {first_name},\n\nJust touching base on my previous email. Let me know if you're interested.",
  "Hi {first_name},\n\nThought you might be interested in a recent case study we published. Let me know if you want to see it.",
  "Hi {first_name},\n\nIs {company} currently prioritizing operational efficiency? If so, we might be a good fit.",
  "Hi {first_name},\n\nI'm reaching out because I have a few thoughts on how {company} could optimize its backend. Can we chat for 5 minutes?",
  "Hi {first_name},\n\nI wanted to share a quick tool that could help your team at {company}. Want me to send the details?",
  "Hi {first_name},\n\nAre you the decision-maker for operations at {company}? If not, could you point me in the right direction?",
  "Hi {first_name},\n\nI'll be brief. We help teams streamline their workflows. Is this something {company} needs?",
  "Hi {first_name},\n\nJust wanted to see if you received my previous message. Let me know if you have any questions.",
  "Hi {first_name},\n\nI was impressed by what {company} is doing and wanted to connect. We help similar companies scale. Open to a chat?",
  "Hi {first_name},\n\nQuick question: how much time does your team spend on backend tasks? We might be able to reduce that significantly.",
  "Hi {first_name},\n\nI know you get a lot of emails. We offer a solution that can automate {company}'s operations. Interested in learning more?",
  "Hi {first_name},\n\nJust following up one last time. If I don't hear back, I'll assume this isn't a priority right now.",
  "Hi {first_name},\n\nThought this guide on scaling operations might be useful for {company}. Let me know if you want a copy.",
  "Hi {first_name},\n\nIs {company} currently dealing with any bottlenecks? We specialize in solving those.",
  "Hi {first_name},\n\nI'm reaching out because I think our tool could be very valuable for {company}. Can we schedule a brief demo?",
  "Hi {first_name},\n\nI wanted to share a quick case study that shows how we helped a similar company. Want to take a look?",
  "Hi {first_name},\n\nAre you currently exploring new ways to improve operations at {company}? We should definitely talk.",
  "Hi {first_name},\n\nI'll keep this short. We automate backend processes. Is {company} looking for this kind of solution?",
  "Hi {first_name},\n\nJust checking in to see if you're the right person to speak with regarding this?",
  "Hi {first_name},\n\nI've been following {company} and think our solution could help you scale more efficiently. Open to a quick call?",
  "Hi {first_name},\n\nQuick question: is {company} currently using any automation tools? We might be able to offer a better alternative.",
  "Hi {first_name},\n\nI know you're busy. We help teams like {company} save time. Want to see how?",
  "Hi {first_name},\n\nJust following up on my previous note. Let me know if this is relevant to you.",
  "Hi {first_name},\n\nThought you might find this whitepaper interesting. Let me know if you want the link."
];

export const htmlTemplates = [
  {
    id: 'plain',
    name: 'Plain Text (High Deliverability)',
    render: (body: string) => body.replace(/\n/g, '<br/>')
  },
  {
    id: 'minimal',
    name: 'Minimalist B2B',
    render: (body: string) => `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333333; line-height: 1.6;">
        <div style="padding: 30px 20px;">
          ${body.replace(/\n/g, '<br/>')}
        </div>
      </div>
    `
  },
  {
    id: 'bold',
    name: 'Bold Dark Mode',
    render: (body: string) => `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #111111; color: #f4f4f5; line-height: 1.6; border-radius: 8px; overflow: hidden;">
        <div style="padding: 40px 30px;">
          ${body.replace(/\n/g, '<br/>')}
        </div>
        <div style="background-color: #000000; padding: 20px 30px; border-top: 1px solid #222222; font-size: 12px; color: #888888;">
          Sent securely via Relay
        </div>
      </div>
    `
  }
];
